### ISSUE TITLE
UI: delete/move "没有更多" label

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#12]
I don't think there's a need to show this "没有更多" label in the bottom, instead, you could:
* loading more items when scrolling up, and display "没有更多" when there's no more messages -- looks like you haven't implemented a pagination thing, right?
* instead, add an "edit" or "new message" line of button(s) at the bottom

BTW, perhaps you forgot to change "没有更多" to "no more messages" -- I see a trend in using English instead of Chinese.

![image](https://user-images.githubusercontent.com/8684355/55920111-2116c400-5c2b-11e9-8c0d-68b4b0b97ea3.png)

**Comment by kezhenxu94** [comment]
> I don't think there's a need to show this "没有更多" label in the bottom, instead, you could:
> 
> * loading more items when scrolling up, and display "没有更多" when there's no more messages -- looks like you haven't implemented a pagination thing, right?
> * instead, add an "edit" or "new message" line of button(s) at the bottom
> 
> BTW, perhaps you forgot to change "没有更多" to "no more messages" -- I see a trend in using English instead of Chinese.
> 
> ![image](https://user-images.githubusercontent.com/8684355/55920111-2116c400-5c2b-11e9-8c0d-68b4b0b97ea3.png)

> loading more items when scrolling up, and display "没有更多" when there's no more messages -- looks like you haven't implemented a pagination thing, right?

Actually it's implemented and works as you described, and the issue you open happened to be no comments :) you can open a heated Issue(with many comments) to see the effect

> instead, add an "edit" or "new message" line of button(s) at the bottom

That's a really awesome advice, adding a "new comment" button at the end of list is natural for userd
