### ISSUE TITLE
Feature Request: loading more items in Issues page and Pulls page

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#13]
The current PRs, issues, or trends only display one page of items (30 items I guess), I think we need to support "loading more items by scrolling up" feature, otherwise, the information is incomplete.

**Comment by johnnychen94** [comment]
I don't have a front-end development background, so the only thing I can help to improve this project is to throw issues and feedbacks to you. Hope you like it. 😃

**Comment by kezhenxu94** [comment]
> I don't have a front-end development background, so the only thing I can help to improve this project is to throw issues and feedbacks to you. Hope you like it.

Sure I like it, reporting bugs and requesting features are definitely contributions! Thanks :)

**Comment by kezhenxu94** [comment]
> The current PRs, issues, or trends only display one page of items (30 items I guess), I think we need to support "loading more items by scrolling up" feature, otherwise, the information is incomplete.

Yes, many pages have **load more** buttons except the Issues and PRs pages, added **load more** in these two pages is in plan, but since you mentioned, I'll try to do it as soon as possible, as for the **trending page** I'm afraid we cannot do anything because GitHub only shows 30 trending repositories or so (that's all)

**Comment by johnnychen94** [comment]
Then you got a lot of stuff to do :) I believe you can manage your time well.

**Comment by kezhenxu94** [comment]
Hi @johnnychen94 , the latest version supports loading more in Issues page and Pulls page, please give it a try, if it doesn't work, feel free to reopen this issue :) thanks

![image](https://user-images.githubusercontent.com/15965696/56627270-a365a600-6677-11e9-95b8-c9d7c2c53889.png)
