### ISSUE TITLE
Bug: priority conflict between link and checkbox

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#14]
When clicking link such as:

- [ ] [readme](https://github.com/kezhenxu94/mini-github/blob/master/README.md)

it will do two things:

* uncheck/check the box
* copy the link

this behavior might be unexcepted.

I guess there're two types of links here: supported link that can be jumped to, and unsupported link that can't. This behavior only happens to the supported links.

**Comment by kezhenxu94** [comment]
Checkboxes are made disabled in the latest version (as what GitHub does), checking/unchecking the checkbox to edit the actual content is another issue, thanks
