### ISSUE TITLE
What's the feed content with user logged out?

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#17]
I thought the **feed** page should contain nothing or "login to get news" (BTW I prefer the name `News` to `Feed`), but it actually contains some relatively meaningless content.

Close this issue if it's your deliberately designed behavior.

**Comment by kezhenxu94** [comment]
The feed content are GitHub global news actually, **news** look good to me

**Comment by kezhenxu94** [comment]
Changed **Feeds** to **News** in the latest version.

> but it actually contains some relatively meaningless content.

It's GitHub global news, I think it's better to show some global news than an empty page
