### ISSUE TITLE
bug: almost empty issue list

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#18]
The problem found in https://github.com/kezhenxu94/mini-github/issues/6 seems not fixed.

![image](https://user-images.githubusercontent.com/8684355/55924108-0d735980-5c3b-11e9-9409-3a9395596573.png)
![image](https://user-images.githubusercontent.com/8684355/55939002-46c5bc80-5c6f-11e9-9928-520c5efcadf4.png)

**Comment by kezhenxu94** [comment]
Fixed in the latest version, thanks for reporting bug 😄
