### ISSUE TITLE
Bug: limited length of message

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#19]
<img src="https://user-images.githubusercontent.com/8684355/56351378-8bb59a00-61ff-11e9-8e3d-4234fbffebd9.png" width="200" height="400" />

LOL I wanna say "BTW this message is sent from mini-github app" but I can input any more words... :joy

Looks like there's a maximum length of comment message. (140-ish) -- or perhaps caused by other issues.

Another UI issue related to comment is that when a comment is posted, it's shown `comment po...` instead of `comment posted` in my iPhone 7.

**Comment by kezhenxu94** [comment]
> Looks like there's a maximum length of comment message. (140-ish) 

Thanks very much for your reporting this, I'll try to work on this ASAP

**Comment by kezhenxu94** [comment]
@johnnychen94 trying to leave a comment that is longer than 140 characters, but note that this is a debug version that's not released yet, hopefully this is long enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough enough

**Comment by kezhenxu94** [comment]
hi @johnnychen94 the comment length limitation is fixed in the latest version

**Comment by johnnychen94** [comment]
@kezhenxu94 cool!👍
