### ISSUE TITLE
mini-github 测试专区 ee

### ISSUE THREAD

**Issue by kzx94** [kezhenxu94/mini-github#23]
@kezhenxu94 提供给小程序用户测试评论等功能的 issue

这是在 mini-github 上修改的内容

**Comment by kezhenxu94** [comment]
@mini-github thanks



> Posted from [mini-github](https://github.com/kezhenxu94/mini-github)
发送自微信小程序 [GitHub 专业版](https://github.com/kezhenxu94/mini-github)

**Comment by mini-github** [comment]
@mini-github test



> Posted from [mini-github](https://github.com/kezhenxu94/mini-github)
发送自微信小程序 [GitHub 专业版](https://github.com/kezhenxu94/mini-github)

**Comment by mini-github** [comment]
test

**Comment by mini-github** [comment]
asdfasdfasd

**Comment by mini-github** [comment]
test again

**Comment by mini-github** [comment]
test aaaaaaaa

**Comment by mini-github** [comment]
testaasdf

**Comment by mini-github** [comment]
teafasdfasdfasdfasdf

**Comment by mini-github** [comment]
测试测试测试i

**Comment by mini-github** [comment]
阿斯顿发送到发送到发的发送到发送到

**Comment by mini-github** [comment]
and

**Comment by mini-github** [comment]
@kezhenxu94 test



> Posted from [mini-github](https://github.com/kezhenxu94/mini-github)
发送自微信小程序 [GitHub 专业版](https://github.com/kezhenxu94/mini-github)

**Comment by mini-github** [comment]
@kezhenxu94 test test



> Posted from [mini-github](https://github.com/kezhenxu94/mini-github)
发送自微信小程序 [GitHub 专业版](https://github.com/kezhenxu94/mini-github)

**Comment by FinnWu** [comment]
test

**Comment by zWingz** [comment]
问下request安全域名有填写`api.github.com` ?
看代码应该是直接通过`cloudfunction`代理

**Comment by kezhenxu94** [comment]
@zWingz 是的，github域名没在国内备案



> Sent from [mini-github](https://github.com/kezhenxu94/mini-github)

**Comment by kezhenxu94** [comment]
test comment in mini-github

**Comment by kezhenxu94** [comment]
@mini-github test comment in a single page

ee

**Comment by kezhenxu94** [comment]
@mini-github testa
