### ISSUE TITLE
Bug: notification type restriction

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#24]
Currently, a new tag will be shown in the notification page, however, clicking it leads to a `status!=200` error. The icon for tag type notification isn't correct either.

![image](https://user-images.githubusercontent.com/8684355/56489648-f6731800-6514-11e9-8578-b937689370ff.png)

![image](https://user-images.githubusercontent.com/8684355/56489781-78634100-6515-11e9-970f-fef17a01617b.png)

**Comment by kezhenxu94** [comment]
fixed in the latest version, thanks @maoqxxmm

**Comment by maoqxxmm** [comment]
Would you mind describing how to get such label in notifications? I've tried but can't get it 😂 @johnnychen94

**Comment by kezhenxu94** [comment]
> Would you mind describing how to get such label in notifications? I've tried but can't get it 😂 @johnnychen94

@maoqxxmm the notification is sent when there is a release in the repository, maybe it's hard to reproduce, but you can try to make a release in this repo to see the notification, you have the privilleges I think.
