### ISSUE TITLE
UI: words Incorrect

### ISSUE THREAD

**Issue by qingwufong** [kezhenxu94/mini-github#26]
Under News Modules, we can see a link which called "Sign In to Seee My News" on the top, Should it be called "Sign In to See My News", is it a type error?

**Comment by kezhenxu94** [comment]
> Under News Modules, we can see a link which called "Sign In to Seee My News" on the top, Should it be called "Sign In to See My News", is it a type error?

It's definitely a typo 😄 will fix it soon, thanks for reporting

**Comment by kezhenxu94** [comment]
fixed in the latest version
