### ISSUE TITLE
多次取消添加star偶尔会出现数字显示出错

### ISSUE THREAD

**Issue by super9du** [kezhenxu94/mini-github#43]
多次取消添加star偶尔会出现数字显示出错，且star添加和不添加没区别

**Comment by ZengyiMa** [comment]
感谢反馈， 是快速点击star按钮的场景下吗？

**Comment by kezhenxu94** [comment]
> 感谢反馈， 是快速点击star按钮的场景下吗？

@ZengyiMa 对的, 可以重现, 快速点击 star 按钮会导致数字不一致, 可以考虑请求接口时让 star 按钮 disable 或 loading

且已 star 的图标应该变色

**Comment by ZengyiMa** [comment]
好的，收到
