### ISSUE TITLE
Enhancement: tag or change items in "Closed PRs" list

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#7]
The current closed PRs list doesn't offer much information because Closed PR is a superset of Merged PR. Take the screenshot as an example: which PRs are closed and which PRs are merged?

A simple and effective solution to this is to list only non-merged closed PRs in the "Closed PRs" list.

Another solution is to tag each item with `merged` or `closed`

![image](https://user-images.githubusercontent.com/8684355/55918937-97fd8e00-5c26-11e9-984c-9eebbcd52c65.png)

**Comment by kezhenxu94** [comment]
> nother solution is to tag each item with merged or closed

I prefer this one, what do you think :) because GitHub webpage shows merged prs in the closed tab too

**Comment by johnnychen94** [comment]
This's the first workaround I came up with, but since you already provide a **Merged** list, there's no need to do so.
