### ISSUE TITLE
UI: badge size

### ISSUE THREAD

**Issue by johnnychen94** [kezhenxu94/mini-github#8]
Badges in `README.md` aren't displayed appropriately; they're too big.

![image](https://user-images.githubusercontent.com/8684355/55919465-b06ea800-5c28-11e9-8c3b-368b9b2c0db8.png)

**Comment by kezhenxu94** [comment]
Hi @johnnychen94  This is fixed in the latest version, please give it a try 😄

**Comment by johnnychen94** [comment]
@kezhenxu94 wow! Looks like you made a lot of changes since then, and I like the current design of repo page.

**Comment by kezhenxu94** [comment]
@johnnychen94 I hope you enjoy it and the notifications page which is newly added, feel free to give feedback 😄
